version: "3.5"
services:
  orion:
    image: fiware/orion:2.2.0
    depends_on:
        - mongo-db
    networks:
        - default
    ports:
        - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG
  mongo-db:
    image: mongo:latest
    ports:
        - "27017:27017"
    networks:
        - default
    command: --bind_ip_all 
  cygnus:
    image: fiware/cygnus-ngsi:latest
    depends_on:
        - mongo-db
    networks:
        - default
    ports:
        - "5051:5051"
        - "5080:5080"
    environment:
        - "CYGNUS_MONGO_HOSTS=mongo-db:27017"
        - "CYGNUS_MONGO_SERVICE_PORT=5051"
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_API_PORT=5080"
        - "CYGNUS_SERVICE_PORT=5051"     
        - "CYGNUS_MONGO_ATTR_PERSISTENCE=column" # data_model
        #- "CYGNUS_MONGO_DATA_MODEL=dm-by-service-path" # data_model
        - "CYGNUS_MONGO_DB_PREFIX=sti_"
        - "CYGNUS_STH_DB_PREFIX=sth_"
        
  postgres-db:
    image: postgres:latest
    ports:
        - "5452:5432"
    networks:
        - default
    environment:
        - "POSTGRES_PASSWORD=1dm3n3str1d4r"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_DB=postgres"
    volumes:
         - pgdata:/var/lib/postgresql/data        
  cygnus-sql:
    image: fiware/cygnus-ngsi:latest
    depends_on:
        - postgres-db
    networks:
        - default
    ports:
        - "5055:5055"
        - "5081:5081"
    environment:
        - "CYGNUS_POSTGRESQL_HOST=postgres-db"
        - "CYGNUS_POSTGRESQL_PORT=5432"
        - "CYGNUS_POSTGRESQL_USER=postgres"
        - "CYGNUS_POSTGRESQL_PASS=1dm3n3str1d4r"
        - "CYGNUS_POSTGRESQL_ENABLE_CACHE=true"
        - "CYGNUS_POSTGRESQL_SERVICE_PORT=5055"
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_API_PORT=5081"
        - "CYGNUS_SERVICE_PORT=5055"
        

  iot-agent:
    image: fiware/iotagent-ul:latest
    depends_on:
        - mongo-db
    networks:
        - default
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo-db
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentul
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041
        
        
        
  metabase-app:
    image: metabase/metabase
    ports:
        - 3000:3000
    restart: "always"
    volumes:
        - ./metabase-data:/metabase-data
    depends_on:
        - postgres-db
    networks:
        - default
    environment:
        - "MB_DB_TYPE=postgres"
        - "MB_DB_DBNAME=postgres"
        - "MB_DB_PORT=5432"
        - "MB_DB_USER=postgres"
        - "MB_DB_PASS=1dm3n3str1d4r"
        - "MB_DB_HOST=postgres-db"
        
volumes: 
     pgdata:   