version: "3.1"
services:

  data-generator:
    image: nunsys/fiware-datagenerator-ue:latest
    hostname: data-generator
    networks:
        - default
    environment:
        - "IOT_AGENT_URL=http://localhost:7896/iot/d"
        - "IOT_AGENT_KEY=4jggokgpepnvsb2uv4s40d5911"

    
